(()=>{
'use strict';
const $=id=>document.getElementById(id),prices={50:250,120:400},cart={50:0,120:0};
const money=n=>'$'+n.toLocaleString('es-MX')+' MXN';
const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const on=(id,event,handler)=>$(id)?.addEventListener(event,handler);
const storageKey='aloe-action-cart-v1';
try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'{}');for(const size of Object.keys(cart)){const count=saved?.[size];cart[size]=Number.isInteger(count)?Math.max(0,Math.min(99,count)):0;}}catch{}
function saveCart(){try{sessionStorage.setItem(storageKey,JSON.stringify(cart));}catch{$('cart-status').textContent='El navegador no permite conservar el carrito entre páginas. La selección sigue disponible en esta página.';}}
let selected=new URLSearchParams(location.search).get('tamano')==='50'?'50':'120',quantity=1;
function updateSelection(){if(!$('quantity'))return;$('quantity').textContent=quantity;$('selection-total').textContent=money(prices[selected]*quantity);$('less').disabled=quantity===1;$('more').disabled=quantity===99;$('size-description').textContent=selected==='50'?'50 ml por $250 MXN. La fotografía de esta presentación está pendiente; la imagen visible muestra el envase de 120 ml.':'120 ml por $400 MXN. La fotografía corresponde a esta presentación.';}
document.querySelectorAll('input[name="size"]').forEach(input=>{input.checked=input.value===selected;input.addEventListener('change',()=>{selected=input.value;updateSelection();$('status').textContent='Seleccionaste '+selected+' ml por '+money(prices[selected])+'.';});});
on('less','click',()=>{quantity=Math.max(1,quantity-1);updateSelection();});on('more','click',()=>{quantity=Math.min(99,quantity+1);updateSelection();});
function renderCart(){const items=Object.keys(cart).filter(size=>cart[size]>0);$('cart-count').textContent=Object.values(cart).reduce((s,n)=>s+n,0);$('cart-total').textContent=money(Object.keys(cart).reduce((s,size)=>s+cart[size]*prices[size],0));$('cart-lines').innerHTML=items.length?items.map(size=>'<article class="cart-line"><h3>Aloe Action · '+size+' ml</h3><p class="small muted">'+money(prices[size])+' por unidad</p><div class="cart-controls"><div class="quantity" role="group" aria-label="Cantidad de '+size+' ml"><button data-size="'+size+'" data-action="less" aria-label="Restar una unidad de '+size+' ml">−</button><output aria-label="Unidades de '+size+' ml">'+cart[size]+'</output><button data-size="'+size+'" data-action="more" '+(cart[size]>=99?'disabled':'')+' aria-label="Sumar una unidad de '+size+' ml">+</button></div><strong>'+money(cart[size]*prices[size])+'</strong></div><button class="remove" data-size="'+size+'" data-action="remove">Quitar '+size+' ml</button></article>').join(''):'<div class="empty"><p>Tu carrito está vacío.</p><a class="text-link" href="/tienda">Explorar presentaciones</a></div>';}
on('add-cart','click',()=>{const added=Math.min(quantity,99-cart[selected]);cart[selected]+=added;renderCart();saveCart();$('status').textContent=added?'Agregaste '+added+' unidad'+(added===1?'':'es')+' de '+selected+' ml. Puedes revisarlas en el carrito.':'Máximo de 99 unidades por presentación en esta demostración.';});
on('open-cart','click',()=>{renderCart();$('cart').showModal();});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
on('cart-lines','click',e=>{const b=e.target.closest('button[data-size]');if(!b)return;const {size,action}=b.dataset;if(action==='remove')cart[size]=0;else cart[size]=Math.max(0,Math.min(99,cart[size]+(action==='more'?1:-1)));renderCart();$('cart-status').textContent='Subtotal actualizado: '+$('cart-total').textContent;saveCart();const next=$('cart-lines').querySelector('button[data-size="'+size+'"][data-action="'+action+'"]:not(:disabled)')||$('cart').querySelector('[data-close]');next.focus();});
function info(title,html){$('info-title').textContent=title;$('info-copy').innerHTML=html;$('info-dialog').showModal();}
on('purchase-process','click',()=>info('El proceso previsto','<p>Este recorrido todavía no está habilitado. No se ha creado ningún pedido.</p><ol><li><strong>Pedido:</strong> confirmar productos y datos.</li><li><strong>Entrega:</strong> validar cobertura, costo y fecha.</li><li><strong>Pago:</strong> habilitar una pasarela segura.</li><li><strong>Guía:</strong> recibir la información de rastreo.</li><li><strong>Embalaje:</strong> preparar el producto.</li><li><strong>Recepción:</strong> confirmar la entrega.</li></ol><p>Operador, plazos y métodos de pago están pendientes de confirmación.</p><a href="/preguntas">Ver preguntas frecuentes</a>'));
on('menu','click',()=>{const open=$('navigation').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('navigation').classList.contains('open')){$('navigation').classList.remove('open');$('menu').setAttribute('aria-expanded','false');$('menu').focus();}});
function filterGlossary(){if(!$('glossary-search'))return;let count=0;document.querySelectorAll('[data-glossary]').forEach(d=>{d.hidden=!normal(d.textContent).includes(normal($('glossary-search').value));if(!d.hidden)count++;});$('glossary-empty').hidden=count>0;}
on('glossary-search','input',filterGlossary);
function openTerm(id,scroll){const d=$(id);if(!d?.matches('[data-glossary]'))return;$('glossary-search').value='';filterGlossary();d.open=true;if(scroll){d.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});d.querySelector('summary').focus({preventScroll:true});}}
document.querySelectorAll('[data-term]').forEach(b=>b.addEventListener('click',()=>{openTerm(b.dataset.term,true);history.replaceState(null,'','#'+b.dataset.term);}));
openTerm(location.hash.slice(1),false);
const searchItems=[['Inicio · Para gente activa','/','marca aloe action comunidad'],['Tienda · Cuidado cotidiano','/tienda','productos precios crema 50 120'],['Aloe Action · Crema corporal','/producto','presentaciones 250 400 comprar'],['Ofertas con condiciones claras','/tienda#promociones','promociones combos'],['Ingredientes y palabras compartidas','/ingredientes','formula aloe centella lavanda mentol vitamina glosario definiciones colaboracion'],['Puntos de venta · Información verificada','/puntos-de-venta','cdmx ubicacion mapa'],['Blog · Ideas y comunidad','/blog','diario articulos intelectual emocional deportivo'],['Nosotros · Nuestro manifiesto','/nosotros','comunidad bienestar valores respeto responsabilidad constancia colaboracion mision vision principios programas'],['Contacto · Conversemos','/contacto','mensaje correo alianzas colaboracion experiencias'],['Preguntas frecuentes','/preguntas','envios entregas pagos pedidos ayuda registro comunidad'],['Privacidad · Tu información','/privacidad','datos almacenamiento responsabilidad']];
function search(){const q=normal($('site-search').value),found=searchItems.filter(x=>normal(x.join(' ')).includes(q));$('search-results').replaceChildren();if(!found.length){$('search-results').textContent='No encontramos resultados. Prueba con “tienda”.';return;}found.forEach(([label,url])=>{const a=document.createElement('a');a.href=url;a.textContent=label;$('search-results').append(a);});}
on('open-search','click',()=>{$('site-search').value='';search();$('search-dialog').showModal();$('site-search').focus();});on('site-search','input',search);
const titles=['Aprender y compartir perspectivas','Relaciones que construyen comunidad','La constancia, a tu ritmo','Compartir capacidades, generar valor'];const storyDescriptions=['Queremos abrir conversaciones sobre aprendizaje e intercambio de ideas, como parte de una vida intelectualmente activa.','Queremos compartir experiencias sobre relaciones humanas, pertenencia y respeto por distintas formas de vivir.','Queremos conocer experiencias de movimiento y hábitos sostenidos, respetando las capacidades y decisiones de cada persona.','Queremos explorar cómo compartir capacidades entre personas, especialistas, comunidades y marcas puede generar beneficio mutuo.'];document.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.story);info(titles[i],'<span class="eyebrow">Línea editorial en preparación</span><p>'+storyDescriptions[i]+'</p><p>Este artículo todavía no está publicado. Revisaremos su contenido y sus fuentes antes de compartirlo.</p><a class="text-link" href="/nosotros">Conoce los principios de nuestro manifiesto</a>');}));
function moveStories(direction){$('stories').scrollBy({left:direction*($('stories').querySelector('.story').getBoundingClientRect().width+24),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}on('stories-prev','click',()=>moveStories(-1));on('stories-next','click',()=>moveStories(1));
on('contact-form','submit',e=>{e.preventDefault();$('draft').hidden=false;$('draft').textContent='Vista previa — no enviada\n\n'+$('contact-name').value.trim()+' · '+$('contact-email').value.trim()+'\n\n'+$('contact-message').value.trim()+'\n\nEste mensaje no se envía ni se almacena.';});
// Preserve links shared before the site was split into individual pages.
if(document.body.dataset.page==='index'){
const legacy={tienda:'/tienda',comprar:'/producto',formula:'/ingredientes',glosario:'/ingredientes#glosario',puntos:'/puntos-de-venta',blog:'/blog',manifiesto:'/nosotros',contacto:'/contacto',preguntas:'/preguntas',promociones:'/tienda#promociones'};
const target=legacy[location.hash.slice(1)];if(target)location.replace(target);
}
updateSelection();renderCart();
})();
